missionInfo = {
    '0': [['coins', ['silver', 'silver', 'gold', 'frozen_silver', 'frozen_gold']], ['pets', 2]],
    '1': [['coins', ['silver', 'silver', 'gold', 'frozen_silver', 'frozen_gold', 'frozen_silver', 'frozen_gold']],
          ['pets', 4]],
    '2': [['coins', ['silver', 'silver', 'gold', 'frozen_silver', 'frozen_gold', 'frozen_silver', 'frozen_gold']],
          ['pets', 3], ['boats', 1]],
    '3': [['coins', ['silver', 'silver']], ['boats', 2]],
    '6': [['coins', ['silver']], ['bridges', 1]],
    '9': [['coins', ['silver', 'silver']], ['coins', 24]],
    '21': [['coins', ['silver', 'silver', 'silver']], ['coins', 10]],
    '22': [['coins', ['silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver']]],
    '30': [['coins', ['silver', 'silver', 'silver']], ['boats', 1], ['coins', 10]],
    '57': [['coins',
            ['silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver',
             'silver', 'silver']], ['coins', 3]],
    '119': [['coins', ['frozen_silver', 'silver', 'gold', 'frozen_gold', 'gold', 'frozen_silver']], ['pets', 1]],

    '10209': [['coins', ['silver', 'silver', 'silver', 'silver']], ['boats', 1]],
    '10210': [['coins', ['silver']], ['boats', 1]],
    '10309': [['coins',
               ['silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver',
                'silver']], ['boats', 1], ['islands', 1]],
    '10510': [['coins', ['frozen_silver', 'frozen_silver', 'frozen_silver', 'frozen_silver']], ['pets', 2],
              ['bridges', 2]],
    '10605': [['coins',
               ['silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver',
                'silver', 'silver', 'silver', 'silver', 'silver']], ['boats', 1], ['boats', 3], ['bridges', 1]],
    '10610': [['coins', ['silver', 'silver', 'silver']], ['boats', 3], ['islands', 10]],
    '10613': [['coins', ['silver', 'silver', 'silver', 'silver']], ['boats', 4], ['islands', 1]],
    '10715': [['coins', ['silver', 'silver', 'silver', 'silver', 'silver', 'silver']], ['boats', 3],
              ['islands', 10], ['rafts', 1]],
    '11002': [['coins', ['gold', 'silver', 'gold']], ['pets', 1], ['boats', 1], ['boats', 1],
              ['islands', 4]],
    '11003': [['coins', ['frozen_gold', 'silver', 'frozen_silver', 'gold', 'frozen_silver']], ['pets', 1],
              ['boats', 2], ['coins', 12]],
    '11004': [['coins', ['silver', 'gold', 'silver', 'gold', 'gold', 'silver']], ['pets', 1], ['boats', 2],
              ['coins', 10]],
    '11008': [['coins', ['gold', 'silver']], ['pets', 1], ['boats', 1], ['coins', 14]],
    '11206': [['coins', ['silver', 'gold', 'silver', 'gold', 'silver', 'silver', 'gold']], ['bridges', 3]],

}